Swap out SimpleDateFormat with DateTimeFormatter
reactor/reactor-kafka pull request #271
Opened 2022-03-08 12:08 UTC by ascopes

SimpleDateFormat is not threadsafe, and so has been swapped out with the threadsafe DateTimeFormatter implementation instead.

2022-03-08 15:20 UTC, simonbasle requested changes

2022-03-08 17:24 UTC, ascopes commented on reactor-kafka-samples/src/main/java/reactor/kafka/samples/SampleProducer.java
> +                      dateFormat.format(Instant.now()));
Should be amended now, thanks for checking.

2022-03-08 20:44 UTC, simonbasle approved these changes

2022-03-11 15:22 UTC, simonbasle approved these changes

2022-03-11 15:23 UTC, simonbasle commented
Thanks for the PR @ascopes, have polished the license headers so that this can be merged today and released on tuesday, as nobody will be able to merge on monday.

2022-03-11 16:05 UTC, merged