Add receive batch to receiver
reactor/reactor-kafka pull request #359
Opened 2023-08-31 14:26 UTC by mohamed-gara

This PR is an implementation to resolve #261. I have chosen the name proposed by @serejke [here](https://github.com/reactor/reactor-kafka/issues/261#issuecomment-1011481582) for the new method in KafkaReceiver.

Actually, in our product I use receive() with the bufferTimeout operator. But it is not the best solution to consume a record 
batch. With the receiveBatch() method batch consumption will be easier.

2023-08-31 14:26 UTC, pivotal-cla commented
@mohamed-gara Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-kafka&pullRequestId=359)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-kafka&pullRequestId=359) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-08-31 14:27 UTC, pivotal-cla commented
@mohamed-gara Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-kafka&pullRequestId=359)!

2023-08-31 19:03 UTC, artembilan requested changes
Just a couple `@since` correction.
Otherwise I don't see any problems with this fix.

Thanks

2023-08-31 19:03 UTC, artembilan commented on src/main/java/reactor/kafka/receiver/KafkaReceiver.java
> +     * @since 1.3.?
```suggestion
     * @since 1.3.21
```

2023-08-31 19:03 UTC, artembilan commented on src/main/java/reactor/kafka/receiver/KafkaReceiver.java
> +     * @since 1.3.?
```suggestion
     * @since 1.3.21
```

2023-08-31 19:59 UTC, mohamed-gara commented on src/main/java/reactor/kafka/receiver/KafkaReceiver.java
> +     * @since 1.3.?
Done.

2023-08-31 20:00 UTC, mohamed-gara commented on src/main/java/reactor/kafka/receiver/KafkaReceiver.java
> +     * @since 1.3.?
The two @since are fixed.

2023-08-31 20:51 UTC, artembilan approved these changes

2023-09-07 17:33 UTC, garyrussell requested changes
LGTM; please add some documentation for the `receiveBatch` method.

https://projectreactor.io/docs/kafka/release/reference/#api-guide-receiver

2023-09-11 13:27 UTC, artembilan approved these changes

2023-09-11 15:43 UTC, garyrussell approved these changes

2023-09-11 15:44 UTC, merged